services:
  nextjs-bot-protection:
    build: .
    command: npm run dev
    labels:
      - dev.orbstack.domains=nextjs-bot-protection.arcjet-examples.orb.local
    env_file:
      - .env.local
    ports:
      - 3000
    volumes:
      - .:/app
      - nextjs-bot-protection_node_modules:/app/node_modules

volumes:
  nextjs-bot-protection_node_modules:
