services:
  nextjs-server-action:
    build: .
    command: npm run dev
    labels:
      - dev.orbstack.domains=nextjs-server-action.arcjet-examples.orb.local
    env_file:
      - .env.local
    ports:
      - 3000
    volumes:
      - .:/app
      - nextjs-server-action_node_modules:/app/node_modules

volumes:
  nextjs-server-action_node_modules:
