services:
  firebase-functions:
    build: .
    command: npm run dev
    env_file:
      - .secret.local
    labels:
      - dev.orbstack.domains=firebase-functions.arcjet-examples.orb.local
    ports:
      - 5000
    volumes:
      - .:/app
      - firebase-functions_node_modules:/app/node_modules

volumes:
  firebase-functions_node_modules:
